### ISSUE TITLE
What is the added value to anti-xss over htmlentities($val, ENT_QUOTES); 

### ISSUE THREAD

**Issue by killua-eu** [voku/anti-xss#57]
Hi, I thought htmlentities() would be a safe way to handle user data, but I guess anti-xss wouldn't exist then. What is the added benefit to security when using anti-xss over htmlentities?

Thanks lots, P.

**Comment by voku** [comment]
It depends ... I think the best way is to don't accept HTML at all ... 

```php
function noHTML(string $input, string $encoding = 'UTF-8'): string
{
    return htmlentities($input, ENT_QUOTES | ENT_HTML5, $encoding);
}
```

... but that is not working every time (mostly because of some user / admin content) and here you can use e.g. "HTML Purifier" (whitelist - http://htmlpurifier.org/demo.php) or this "AntiXSS" (blacklist - http://anti-xss-demo.suckup.de/). Whitelisting is maybe more secure but you need to configure all allowed HTML tags and attributes by yourself and this is again hard with HTML5 and custom elements and custom data-* attributes.

- https://paragonie.com/blog/2015/06/preventing-xss-vulnerabilities-in-php-everything-you-need-know
- https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.md

**Comment by killua-eu** [comment]
After some testing on how anti-xss and htmlentities/noHTML() combine with the rest of my stack, and after looking at https://github.com/voku/anti-xss/blob/master/tests/JsXssTest.php, i came to the conclusion, that anti-xss is the better choice for now (keeps more things usable).
